import type { Student, Teacher, Class, Subject, Fee, User, Mark, Exam, Attendance, Payment } from './types';
import { placeholderImages } from './placeholder-images.json';

export const users: User[] = [
  { id: 'user-1', name: 'Admin User', email: 'admin@gits.ac.ke', role: 'Admin', avatarUrl: placeholderImages[0].imageUrl },
  { id: 'user-2', name: 'Dean User', email: 'dean@gits.ac.ke', role: 'Dean', avatarUrl: placeholderImages[1].imageUrl },
  { id: 'user-3', name: 'Teacher User', email: 'teacher@gits.ac.ke', role: 'Teacher', avatarUrl: placeholderImages[2].imageUrl },
  { id: 'user-4', name: 'Accountant User', email: 'accountant@gits.ac.ke', role: 'Accountant', avatarUrl: placeholderImages[3].imageUrl },
];

export const students: Student[] = [
  { id: 'std-1', admissionNumber: 'GHS-001', name: 'Alice Johnson', classId: 'cls-1', guardianName: 'John Johnson', guardianPhone: '0712345678', avatarUrl: placeholderImages[4].imageUrl, dateOfBirth: '2008-05-10' },
  { id: 'std-2', admissionNumber: 'GHS-002', name: 'Bob Williams', classId: 'cls-1', guardianName: 'Jane Williams', guardianPhone: '0723456789', avatarUrl: placeholderImages[5].imageUrl, dateOfBirth: '2008-03-15' },
  { id: 'std-3', admissionNumber: 'GHS-003', name: 'Charlie Brown', classId: 'cls-2', guardianName: 'Chris Brown', guardianPhone: '0734567890', avatarUrl: placeholderImages[6].imageUrl, dateOfBirth: '2007-11-20' },
  { id: 'std-4', admissionNumber: 'GHS-004', name: 'Diana Miller', classId: 'cls-3', guardianName: 'David Miller', guardianPhone: '0745678901', avatarUrl: placeholderImages[7].imageUrl, dateOfBirth: '2009-01-30' },
  { id: 'std-5', admissionNumber: 'GHS-005', name: 'Ethan Davis', classId: 'cls-2', guardianName: 'Emily Davis', guardianPhone: '0756789012', avatarUrl: placeholderImages[8].imageUrl, dateOfBirth: '2007-09-05' },
  { "id": "std-4710", "admissionNumber": "4710", "name": "NJAMBI CLEMENCY GIFT", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4710/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4717", "admissionNumber": "4717", "name": "LUSIRE ELIZABETH NJOKI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4717/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4496", "admissionNumber": "4496", "name": "KASHU TERESIA NAIRESIAE", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4496/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4894", "admissionNumber": "4894", "name": "BIYOKI FAITH NYABOKE", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4894/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4699", "admissionNumber": "4699", "name": "OGETO MARKLINE MORAA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4699/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4906", "admissionNumber": "4906", "name": "INDUVIRU PRUDENCE ADAMBA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4906/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4935", "admissionNumber": "4935", "name": "KORIR MERCY CHELANGAT", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4935/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4497", "admissionNumber": "4497", "name": "KALIBO IVY NALIAKA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4497/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-5121", "admissionNumber": "5121", "name": "KARIUKI MORGAN MAINA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/5121/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4718", "admissionNumber": "4718", "name": "NDUTA PURITY NYOKABI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4718/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4742", "admissionNumber": "4742", "name": "NDUNGU STANLEY NGANGA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4742/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-5136", "admissionNumber": "5136", "name": "KIMANI DERRICK WAWERU", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/5136/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-6247", "admissionNumber": "6247", "name": "MARION KERUBO", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/6247/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4814", "admissionNumber": "4814", "name": "OMBATI AGNA MORAA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4814/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-6301", "admissionNumber": "6301", "name": "KAMAU ASHLEY WANGECHI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/6301/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4758", "admissionNumber": "4758", "name": "NJOROGE ANTHONEY GIKONYO", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4758/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-5845", "admissionNumber": "5845", "name": "FAITH NJERI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/5845/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-5018", "admissionNumber": "5018", "name": "MUSYOKA HANNAH KANINI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/5018/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4747", "admissionNumber": "4747", "name": "WANJIRU MARGARET NJERI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4747/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-5647", "admissionNumber": "5647", "name": "Timothy Mulinge", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/5647/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4793", "admissionNumber": "4793", "name": "MMBOKA DANIEL MWITA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4793/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4858", "admissionNumber": "4858", "name": "GITAU VIRGINIA WANJIRU", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4858/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-3977", "admissionNumber": "3977", "name": "EKITELA MUSA LOCHOK", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/3977/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-6274", "admissionNumber": "6274", "name": "Nyamboke Happy", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/6274/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4697", "admissionNumber": "4697", "name": "KIMANI STEVE MBURU", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4697/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4768", "admissionNumber": "4768", "name": "NJUGUNA MARY WANGUI", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4768/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4745", "admissionNumber": "4745", "name": "LODIAKA RUTH LOWOTHA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4745/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-5125", "admissionNumber": "5125", "name": "NDILA AMOS KIVUVA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/5125/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4755", "admissionNumber": "4755", "name": "IREGI FRANCISCA", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4755/200/300", "dateOfBirth": "2009-01-01" },
  { "id": "std-4812", "admissionNumber": "4812", "name": "MACHARIA COSMAS NDUNGU", "classId": "cls-4", "guardianName": "", "guardianPhone": "", "avatarUrl": "https://picsum.photos/seed/4812/200/300", "dateOfBirth": "2009-01-01" }
];

export const teachers: Teacher[] = [
  { id: 'tch-1', staffId: 'TS-01', name: 'Mr. Peter Jones', subjectIds: ['sub-1', 'sub-2'], email: 'peter.jones@gits.ac.ke', phone: '0701234567', avatarUrl: placeholderImages[9].imageUrl },
  { id: 'tch-2', staffId: 'TS-02', name: 'Ms. Susan White', subjectIds: ['sub-3', 'sub-4'], email: 'susan.white@gits.ac.ke', phone: '0702345678', avatarUrl: placeholderImages[10].imageUrl },
  { id: 'tch-3', staffId: 'TS-03', name: 'Mr. Ken Omondi', subjectIds: ['sub-5', 'sub-6'], email: 'ken.omondi@gits.ac.ke', phone: '0703456789', avatarUrl: placeholderImages[11].imageUrl },
];

export const classes: Class[] = [
  { id: 'cls-1', name: 'Form 1', stream: 'A', classTeacherId: 'tch-1' },
  { id: 'cls-5', name: 'Form 1', stream: 'B', classTeacherId: 'tch-2' },
  { id: 'cls-2', name: 'Form 2', stream: 'B', classTeacherId: 'tch-2' },
  { id: 'cls-3', name: 'Form 3', stream: 'C', classTeacherId: 'tch-3' },
  { id: 'cls-4', name: 'Form 4', stream: 'Blue', classTeacherId: 'tch-1' },
  { id: 'cls-6', name: 'Form 1', stream: 'B', classTeacherId: 'tch-2' },
];

export const subjects: Subject[] = [
  { id: 'sub-1', name: 'Mathematics', code: '121' },
  { id: 'sub-2', name: 'English', code: '101' },
  { id: 'sub-3', name: 'Kiswahili', code: '102' },
  { id: 'sub-4', name: 'Physics', code: '232' },
  { id: 'sub-5', name: 'Chemistry', code: '233' },
  { id: 'sub-6', name: 'Biology', code: '231' },
  { id: 'sub-7', name: 'History', code: '311' },
  { id: 'sub-8', name: 'Geography', code: '312' },
  { id: 'sub-9', name: 'CRE', code: '313' },
  { id: 'sub-10', name: 'Home Science', code: '441' },
  { id: 'sub-11', name: 'Agriculture', code: '443' },
  { id: 'sub-12', name: 'Computer Studies', code: '451' },
  { id: 'sub-13', name: 'French', code: '501' },
  { id: 'sub-14', name: 'German', code: '502' },
  { id: 'sub-15', name: 'Business Studies', code: '565' },
];

export const exams: Exam[] = [
    { id: 'exam-1', name: 'Term 1 Opener', term: '1', year: 2024 },
    { id: 'exam-2', name: 'Term 1 Mid-Term', term: '1', year: 2024 },
    { id: 'exam-3', name: 'Term 1 End-Term', term: '1', year: 2024 },
    { id: 'exam-4', name: 'Term 2 2025', term: '2', year: 2025 },
];

export const marks: Mark[] = [
  { studentId: 'std-1', subjectId: 'sub-1', examId: 'exam-1', score: 78 },
  { studentId: 'std-1', subjectId: 'sub-2', examId: 'exam-1', score: 82 },
  { studentId: 'std-1', subjectId: 'sub-3', examId: 'exam-1', score: 75 },
  { studentId: 'std-2', subjectId: 'sub-1', examId: 'exam-1', score: 65 },
  { studentId: 'std-2', subjectId: 'sub-2', examId: 'exam-1', score: 71 },
  { studentId: 'std-2', subjectId: 'sub-3', examId: 'exam-1', score: 68 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-2", "score": 82 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-3", "score": 86 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-1", "score": 86 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-6", "score": 78 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-4", "score": 80 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-5", "score": 92 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-8", "score": 96 },
  { "studentId": "std-4710", "examId": "exam-4", "subjectId": "sub-11", "score": 90 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-2", "score": 70 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-3", "score": 78 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-1", "score": 92 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-6", "score": 28 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-4", "score": 74 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-5", "score": 80 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-8", "score": 90 },
  { "studentId": "std-4717", "examId": "exam-4", "subjectId": "sub-11", "score": 74 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-2", "score": 54 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-3", "score": 88 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-1", "score": 98 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-6", "score": 58 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-5", "score": 62 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-7", "score": 74 },
  { "studentId": "std-4496", "examId": "exam-4", "subjectId": "sub-9", "score": 80 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-2", "score": 62 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-3", "score": 86 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-1", "score": 88 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-6", "score": 42 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-5", "score": 82 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-9", "score": 56 },
  { "studentId": "std-4894", "examId": "exam-4", "subjectId": "sub-15", "score": 84 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-2", "score": 84 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-3", "score": 72 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-1", "score": 86 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-6", "score": 44 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-4", "score": 56 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-5", "score": 54 },
  { "studentId": "std-4699", "examId": "exam-4", "subjectId": "sub-9", "score": 80 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-2", "score": 58 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-3", "score": 80 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-1", "score": 88 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-6", "score": 32 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-4", "score": 58 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-5", "score": 66 },
  { "studentId": "std-4906", "examId": "exam-4", "subjectId": "sub-8", "score": 72 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-2", "score": 58 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-3", "score": 56 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-1", "score": 86 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-6", "score": 58 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-5", "score": 76 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-7", "score": 24 },
  { "studentId": "std-4935", "examId": "exam-4", "subjectId": "sub-9", "score": 60 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-2", "score": 40 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-3", "score": 76 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-1", "score": 68 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-6", "score": 48 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-4", "score": 16 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-5", "score": 56 },
  { "studentId": "std-4497", "examId": "exam-4", "subjectId": "sub-8", "score": 74 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-2", "score": 74 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-3", "score": 50 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-1", "score": 82 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-6", "score": 46 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-4", "score": 42 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-5", "score": 58 },
  { "studentId": "std-5121", "examId": "exam-4", "subjectId": "sub-15", "score": 74 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-2", "score": 52 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-3", "score": 68 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-1", "score": 74 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-6", "score": 22 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-5", "score": 42 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-8", "score": 80 },
  { "studentId": "std-4718", "examId": "exam-4", "subjectId": "sub-9", "score": 68 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-2", "score": 48 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-3", "score": 50 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-1", "score": 94 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-6", "score": 32 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-4", "score": 56 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-5", "score": 66 },
  { "studentId": "std-4742", "examId": "exam-4", "subjectId": "sub-9", "score": 68 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-2", "score": 48 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-3", "score": 42 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-1", "score": 62 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-6", "score": 34 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-4", "score": 58 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-5", "score": 56 },
  { "studentId": "std-5136", "examId": "exam-4", "subjectId": "sub-8", "score": 78 },
  { "studentId": "std-6247", "examId": "exam-4", "subjectId": "sub-2", "score": 74 },
  { "studentId": "std-6247", "examId": "exam-4", "subjectId": "sub-1", "score": 80 },
  { "studentId": "std-6247", "examId": "exam-4", "subjectId": "sub-6", "score": 20 },
  { "studentId": "std-6247", "examId": "exam-4", "subjectId": "sub-5", "score": 54 },
  { "studentId": "std-6247", "examId": "exam-4", "subjectId": "sub-7", "score": 86 },
  { "studentId": "std-6247", "examId": "exam-4", "subjectId": "sub-9", "score": 72 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-2", "score": 58 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-3", "score": 58 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-1", "score": 78 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-6", "score": 36 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-4", "score": 54 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-5", "score": 52 },
  { "studentId": "std-4814", "examId": "exam-4", "subjectId": "sub-9", "score": 56 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-2", "score": 40 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-3", "score": 50 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-1", "score": 68 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-6", "score": 4 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-5", "score": 48 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-8", "score": 82 },
  { "studentId": "std-6301", "examId": "exam-4", "subjectId": "sub-9", "score": 78 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-2", "score": 54 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-3", "score": 56 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-1", "score": 64 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-6", "score": 52 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-4", "score": 30 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-5", "score": 26 },
  { "studentId": "std-4758", "examId": "exam-4", "subjectId": "sub-9", "score": 76 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-2", "score": 62 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-3", "score": 50 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-1", "score": 48 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-6", "score": 38 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-5", "score": 34 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-8", "score": 62 },
  { "studentId": "std-5845", "examId": "exam-4", "subjectId": "sub-9", "score": 76 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-2", "score": 46 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-3", "score": 68 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-1", "score": 54 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-6", "score": 12 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-4", "score": 32 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-5", "score": 46 },
  { "studentId": "std-5018", "examId": "exam-4", "subjectId": "sub-15", "score": 72 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-2", "score": 44 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-3", "score": 42 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-1", "score": 88 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-6", "score": 24 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-5", "score": 32 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-7", "score": 72 },
  { "studentId": "std-4747", "examId": "exam-4", "subjectId": "sub-15", "score": 74 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-2", "score": 60 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-3", "score": 52 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-1", "score": 48 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-6", "score": 46 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-4", "score": 14 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-7", "score": 68 },
  { "studentId": "std-5647", "examId": "exam-4", "subjectId": "sub-9", "score": 66 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-2", "score": 46 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-3", "score": 52 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-1", "score": 80 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-6", "score": 32 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-5", "score": 28 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-7", "score": 70 },
  { "studentId": "std-4793", "examId": "exam-4", "subjectId": "sub-9", "score": 54 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-2", "score": 68 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-3", "score": 46 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-1", "score": 50 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-6", "score": 20 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-5", "score": 28 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-9", "score": 64 },
  { "studentId": "std-4858", "examId": "exam-4", "subjectId": "sub-15", "score": 74 },
  { "studentId": "std-3977", "examId": "exam-4", "subjectId": "sub-2", "score": 54 },
  { "studentId": "std-3977", "examId": "exam-4", "subjectId": "sub-3", "score": 50 },
  { "studentId": "std-3977", "examId": "exam-4", "subjectId": "sub-6", "score": 42 },
  { "studentId": "std-3977", "examId": "exam-4", "subjectId": "sub-5", "score": 20 },
  { "studentId": "std-3977", "examId": "exam-4", "subjectId": "sub-7", "score": 54 },
  { "studentId": "std-3977", "examId": "exam-4", "subjectId": "sub-9", "score": 80 },
  { "studentId": "std-6274", "examId": "exam-4", "subjectId": "sub-2", "score": 48 },
  { "studentId": "std-6274", "examId": "exam-4", "subjectId": "sub-3", "score": 50 },
  { "studentId": "std-6274", "examId": "exam-4", "subjectId": "sub-1", "score": 72 },
  { "studentId": "std-6274", "examId": "exam-4", "subjectId": "sub-6", "score": 20 },
  { "studentId": "std-6274", "examId": "exam-4", "subjectId": "sub-7", "score": 60 },
  { "studentId": "std-6274", "examId": "exam-4", "subjectId": "sub-9", "score": 60 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-2", "score": 48 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-3", "score": 42 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-1", "score": 56 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-6", "score": 28 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-5", "score": 20 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-7", "score": 56 },
  { "studentId": "std-4697", "examId": "exam-4", "subjectId": "sub-9", "score": 76 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-2", "score": 58 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-3", "score": 32 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-1", "score": 66 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-6", "score": 34 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-4", "score": 4 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-5", "score": 22 },
  { "studentId": "std-4768", "examId": "exam-4", "subjectId": "sub-9", "score": 80 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-2", "score": 56 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-3", "score": 56 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-1", "score": 44 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-6", "score": 18 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-5", "score": 32 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-7", "score": 58 },
  { "studentId": "std-4745", "examId": "exam-4", "subjectId": "sub-9", "score": 36 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-2", "score": 46 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-3", "score": 54 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-1", "score": 64 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-6", "score": 2 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-4", "score": 20 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-5", "score": 16 },
  { "studentId": "std-5125", "examId": "exam-4", "subjectId": "sub-9", "score": 46 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-2", "score": 54 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-3", "score": 58 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-1", "score": 34 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-6", "score": 24 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-5", "score": 10 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-7", "score": 50 },
  { "studentId": "std-4755", "examId": "exam-4", "subjectId": "sub-9", "score": 66 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-2", "score": 52 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-3", "score": 26 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-1", "score": 52 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-6", "score": 30 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-5", "score": 48 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-7", "score": 38 },
  { "studentId": "std-4812", "examId": "exam-4", "subjectId": "sub-9", "score": 42 }
];

export const fees: Fee[] = [
  { invoiceId: 'inv-001', studentId: 'std-1', amount: 50000, dueDate: '2024-09-01', paidAmount: 50000, balance: 0, status: 'Paid' },
  { invoiceId: 'inv-002', studentId: 'std-2', amount: 50000, dueDate: '2024-09-01', paidAmount: 25000, balance: 25000, status: 'Partial' },
  { invoiceId: 'inv-003', studentId: 'std-3', amount: 52000, dueDate: '2024-09-01', paidAmount: 0, balance: 52000, status: 'Unpaid' },
  { invoiceId: 'inv-004', studentId: 'std-4', amount: 48000, dueDate: '2024-09-01', paidAmount: 48000, balance: 0, status: 'Paid' },
];

export const attendance: Attendance[] = [
    { studentId: 'std-1', date: '2024-07-28', status: 'Present' },
    { studentId: 'std-2', date: '2024-07-28', status: 'Absent' },
    { studentId: 'std-1', date: '2024-07-29', status: 'Present' },
    { studentId: 'std-2', date: '2024-07-29', status: 'Present' },
];

export const payments: Payment[] = [
    { paymentId: 'pay-1', studentId: 'std-1', invoiceId: 'inv-001', amount: 25000, date: '2024-07-20T10:00:00Z' },
    { paymentId: 'pay-2', studentId: 'std-1', invoiceId: 'inv-001', amount: 25000, date: '2024-08-15T14:30:00Z' },
    { paymentId: 'pay-3', studentId: 'std-2', invoiceId: 'inv-002', amount: 25000, date: '2024-08-01T09:00:00Z' },
    { paymentId: 'pay-4', studentId: 'std-4', invoiceId: 'inv-004', amount: 48000, date: '2024-07-25T11:00:00Z' },
];




